In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
from scipy.stats import linregress
pd.set_option('max_colwidth', 400)

#  Dataset 1 - Country Genres

In [2]:
raw_country_genres_df = pd.read_csv('Raw/favorite_music_genres_by_country.csv')

In [3]:
raw_country_genres_df.head()

     Country  Hip hop/Rap/R&b  EDM  Pop  Rock/Metal  Latin/Reggaeton  Other
0  australia               31   15   65          17                0      8
1     canada               39   12   64          14                0     10
2      china               11   23  108           4                0     21
3      india               25    1   39           0                0     55
4     mexico               38    0   18           2               57     43

In [4]:
raw_country_genres_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country          73 non-null     object
 1   Hip hop/Rap/R&b  73 non-null     int64
 2   EDM              73 non-null     int64
 3   Pop              73 non-null     int64
 4   Rock/Metal       73 non-null     int64
 5   Latin/Reggaeton  73 non-null     int64
 6   Other            73 non-null     int64
dtypes: int64(6), object(1)
memory usage: 4.1+ KB

In [5]:
# Exclude 'Country' and 'Highest Genre'
column_limit = raw_country_genres_df.columns[1:-1]  

# Find the column with the highest value for each row (excluding 'Country' and 'Highest Genre') and store it in a new column
raw_country_genres_df['Most Popular Genre'] = raw_country_genres_df[column_limit].idxmax(axis=1)

# Display the updated dataframe
raw_country_genres_df.head()

,Country,Hip hop/Rap/R&b,EDM,Pop,Rock/Metal,Latin/Reggaeton,Other,Most Popular Genre
0,australia,31,15,65,17,0,8,Pop
1,canada,39,12,64,14,0,10,Pop
2,china,11,23,108,4,0,21,Pop
3,india,25,1,39,0,0,55,Pop
4,mexico,38,0,18,2,57,43,Latin/Reggaeton

# Dataset 1 - Spotify Songs

In [6]:
# Read the data into a Pandas DataFrame
raw_spotify_data_df = pd.read_csv('Raw/best_songs_on_spotify_from_2000_to_2023(Cleaned).csv')
columns = ['Title',
           'Artist',
           'Genre',
           'Year',
           'Bpm',
           'Energy',
           'Danceability',
           'dB',
           'Liveness',
           'Valence',
           'Duration (in seconds)',
           'Acousticness',
           'Speechiness',
           'Spotify Rating']
raw_spotify_data_df[columns] = raw_spotify_data_df['title;artist;top genre;year;bpm;energy;danceability ;dB;liveness;valence;duration;acousticness;speechiness ;popularity'].str.split(';', expand=True)
raw_spotify_data_df = raw_spotify_data_df[columns]
raw_spotify_data_df.head()

,Title,Artist,Genre,Year,Bpm,Energy,Danceability,dB,Liveness,Valence,Duration (in seconds),Acousticness,Speechiness,Spotify Rating
0,#thatPOWER,will.i.am,dance pop,2013,128,61,80,-6,7,40,280,0,6,68
1,(When You Gonna) Give It Up to Me (feat. Keyshia Cole) - Radio Version,Sean Paul,dance pop,2006,96,76,71,-3,4,72,244,7,23,68
2,...Baby One More Time,Britney Spears,dance pop,1999,93,70,76,-6,44,91,211,20,3,81
3,★,David Bowie,art rock,2016,98,53,36,-9,18,12,598,21,3,50
4,03' Bonnie & Clyde,JAY-Z,east coast hip hop,2002,90,68,76,-5,15,33,206,23,31,73

In [7]:
raw_spotify_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2385 entries, 0 to 2384
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  2385 non-null   object
 1   Artist                 2385 non-null   object
 2   Genre                  2385 non-null   object
 3   Year                   2385 non-null   object
 4   Bpm                    2385 non-null   object
 5   Energy                 2385 non-null   object
 6   Danceability           2385 non-null   object
 7   dB                     2385 non-null   object
 8   Liveness               2385 non-null   object
 9   Valence                2385 non-null   object
 10  Duration (in seconds)  2385 non-null   object
 11  Acousticness           2385 non-null   object
 12  Speechiness            2385 non-null   object
 13  Spotify Rating         2385 non-null   object
dtypes: object(14)
memory usage: 261.0+ KB

In [8]:
int_columns = ['Year',
               'Bpm',
               'Energy',
               'Danceability',
               'dB',
               'Liveness',
               'Valence',
               'Duration (in seconds)',
               'Acousticness',
               'Speechiness',
               'Spotify Rating']

raw_spotify_data_df[int_columns] = raw_spotify_data_df[int_columns].apply(pd.to_numeric)

In [9]:
raw_spotify_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2385 entries, 0 to 2384
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  2385 non-null   object
 1   Artist                 2385 non-null   object
 2   Genre                  2385 non-null   object
 3   Year                   2385 non-null   int64
 4   Bpm                    2385 non-null   int64
 5   Energy                 2385 non-null   int64
 6   Danceability           2385 non-null   int64
 7   dB                     2385 non-null   int64
 8   Liveness               2385 non-null   int64
 9   Valence                2385 non-null   int64
 10  Duration (in seconds)  2385 non-null   int64
 11  Acousticness           2385 non-null   int64
 12  Speechiness            2385 non-null   int64
 13  Spotify Rating         2385 non-null   int64
dtypes: int64(11), object(3)
memory usage: 261.0+ KB

In [10]:
# Define the mapping of genres
genre_mapping = {
    'hip hop|rap|r&b': 'Hip hop/Rap/R&b',
    'edm|electronic|house|dubstep|trance|electro': 'EDM',
    'pop|dance': 'Pop',
    'rock|metal|thrash|emo|alternative': 'Rock/Metal',
    'latin|reggaeton': 'Latin/Reggaeton'
}

# Iterate over each row in the DataFrame
for index, row in raw_spotify_data_df.iterrows():
    genre = row['Genre']
    updated_genre = 'Other'  # Default value if the genre doesn't match any criteria

    # Check if the genre matches any mapping
    for key, value in genre_mapping.items():
        if any(pd.Series(genre).str.contains(r'\b{}\b'.format(g), case=False, regex=True).any() for g in key.split('|')):
            updated_genre = value
            break  # Stop searching once a match is found

    # Update the 'Genre' column with the mapped genre
    raw_spotify_data_df.at[index, 'Genre'] = updated_genre
    
raw_spotify_data_df.head()

,Title,Artist,Genre,Year,Bpm,Energy,Danceability,dB,Liveness,Valence,Duration (in seconds),Acousticness,Speechiness,Spotify Rating
0,#thatPOWER,will.i.am,Pop,2013,128,61,80,-6,7,40,280,0,6,68
1,(When You Gonna) Give It Up to Me (feat. Keyshia Cole) - Radio Version,Sean Paul,Pop,2006,96,76,71,-3,4,72,244,7,23,68
2,...Baby One More Time,Britney Spears,Pop,1999,93,70,76,-6,44,91,211,20,3,81
3,★,David Bowie,Rock/Metal,2016,98,53,36,-9,18,12,598,21,3,50
4,03' Bonnie & Clyde,JAY-Z,Hip hop/Rap/R&b,2002,90,68,76,-5,15,33,206,23,31,73

# Exporting Cleaned Data

In [11]:
raw_spotify_data_df.to_csv("Clean/cleaned_spotify_data.csv", index=False)

raw_country_genres_df.to_csv("Clean/cleaned_country_data.csv", index=False)